// Arabic translation dictionary for Next Vision Agency.
// Must be loaded BEFORE i18n.js. Keys correspond to data-i18n="..." attributes
// scattered across the *.dc.html pages.
window.NV_AR_DICT = {
  // ---- Nav.dc.html ----
  "nav.home": "الرئيسية",
  "nav.services": "خدماتنا",
  "nav.portfolio": "أعمالنا",
  "nav.about": "من نحن",
  "nav.contact": "تواصل معنا",
  "nav.cta": "ابدأ الآن",

  // ---- Footer.dc.html (also used by the inline footer copy on the home page) ----
  "footer.tagline": "وكالة رقمية تحوّل الأفكار إلى تجارب رقمية استثنائية.",
  "footer.quickLinks": "روابط سريعة",
  "footer.linkHome": "الرئيسية",
  "footer.linkServices": "خدماتنا",
  "footer.linkPortfolio": "أعمالنا",
  "footer.linkAbout": "من نحن",
  "footer.linkContact": "تواصل معنا",
  "footer.servicesTitle": "الخدمات",
  "footer.svcWeb": "تصميم المواقع",
  "footer.svcMobile": "تطبيقات الجوال",
  "footer.svcBrand": "الهوية التجارية",
  "footer.svcSeo": "تحسين محركات البحث والتسويق",
  "footer.svcSupport": "الدعم الفني",
  "footer.contactTitle": "تواصل معنا",
  "footer.location": "الجزائر العاصمة، الجزائر",
  "footer.copyright": "© 2026 Next Vision Agency. جميع الحقوق محفوظة.",

  // ---- Next Vision Agency.dc.html (home page) ----
  "home.hero.eyebrow": "ابتكار رقمي. أثر حقيقي.",
  "home.hero.title1": "نصمم تجارب رقمية",
  "home.hero.title2": "تدفع بعملك",
  "home.hero.title3": "نحو النمو",
  "home.hero.subtitle": "وكالة رقمية متكاملة الخدمات، نصمم مواقع إلكترونية وتطبيقات جوال وهويات تجارية تتواصل مع جمهورك وتحوّله إلى عملاء.",
  "home.hero.ctaPrimary": "ابدأ مشروعك",
  "home.hero.ctaSecondary": "شاهد أعمالنا",

  "home.stats.projects": "مشروعًا تم تسليمه",
  "home.stats.clients": "عميل سعيد",
  "home.stats.years": "سنوات من الخبرة",
  "home.stats.satisfaction": "رضا العملاء",

  "home.services.eyebrow": "ما نقدمه",
  "home.services.title1": "حلول رقمية مصممة",
  "home.services.title2To": "لتحقيق",
  "home.services.title2Goals": "أهدافك",
  "home.services.subtitle": "نجمع بين الإبداع والتقنية والاستراتيجية لتقديم حلول تعزز علامتك التجارية.",

  "home.svc.web.title": "تصميم المواقع",
  "home.svc.web.desc": "مواقع إلكترونية جميلة ومتجاوبة تعكس هويتك وتحقق النتائج.",
  "home.svc.mobile.title": "تطبيقات الجوال",
  "home.svc.mobile.desc": "تطبيقات جوال عالية الأداء لنظامي iOS وAndroid يعشقها المستخدمون.",
  "home.svc.brand.title": "الهوية التجارية",
  "home.svc.brand.desc": "هويات بصرية قوية تجعل علامتك التجارية لا تُنسى وموثوقة.",
  "home.svc.exploreMore": "اكتشف المزيد",

  "home.portfolio.eyebrow": "أعمالنا",
  "home.portfolio.title": "مشاريع مختارة",
  "home.portfolio.viewAll": "عرض جميع المشاريع",

  "home.proj1.title": "منصة تجارة إلكترونية",
  "home.proj1.category": "تطوير المواقع",
  "home.proj2.title": "تطبيق توصيل الطعام",
  "home.proj2.category": "تطبيق جوال",
  "home.proj3.title": "هوية شركة تقنية ناشئة",
  "home.proj3.category": "الهوية التجارية",
  "home.proj4.title": "بوابة عقارية",
  "home.proj4.category": "تطوير المواقع",

  "home.testi.eyebrow": "آراء العملاء",
  "home.testi.titlePlain": "ماذا يقول ",
  "home.testi.titleHighlight": "عملاؤنا",

  "home.testi1.quote": "«غيّرت Next Vision حضورنا الرقمي بالكامل. الموقع الذي بنوه سريع وجميل ويحوّل الزوار إلى عملاء.»",
  "home.testi1.name": "أحمد ك.",
  "home.testi1.role": "الرئيس التنفيذي، LoftReal Homes",

  "home.testi2.quote": "«تطبيق الجوال الذي طوروه لنا فاق كل التوقعات. فريق محترف، تسليم في الوقت المحدد، وتواصل ممتاز.»",
  "home.testi2.name": "سارة م.",
  "home.testi2.role": "المؤسسة، DineBox",

  "home.testi3.quote": "«أعادت Next Vision تصور هويتنا التجارية بالكامل. الشعار والألوان والعناصر تعبّر حقًا عن هويتنا.»",
  "home.testi3.name": "كريم و.",
  "home.testi3.role": "مدير التسويق، Al-Aqsa Corp",

  "home.testi4.quote": "«كنت متشككًا في البداية، لكن Next Vision قدّمت أكثر مما تخيلت. أنصح بشدة بخدماتهم.»",
  "home.testi4.name": "لينا ح.",
  "home.testi4.role": "صاحبة متجر إلكتروني",

  "home.why.eyebrow": "لماذا Next Vision",
  "home.why.title1": "مختلفون في البناء.",
  "home.why.title2": "مبنيّون من أجلك.",
  "home.why.subtitle": "نتّبع منهجية مثبتة لتحويل الأفكار إلى منتجات رقمية قوية.",
  "home.why.learnMore": "اعرف المزيد",

  "home.why1.title": "تسليم سريع",
  "home.why1.desc": "نقدّر وقتك ونلتزم بالمواعيد المحددة.",
  "home.why2.title": "جودة فائقة",
  "home.why2.desc": "نصنعها بدقة واهتمام بأدق التفاصيل.",
  "home.why3.title": "دعم على مدار الساعة",
  "home.why3.desc": "نحن دائمًا هنا لدعمك.",
  "home.why4.title": "تقنيات حديثة",
  "home.why4.desc": "نستخدم أحدث التقنيات لحلول قابلة للتوسع.",
  "home.why5.title": "محسّن لمحركات البحث",
  "home.why5.desc": "مبني وفق أفضل الممارسات لتصدّر نتائج البحث.",
  "home.why6.title": "مخصص بالكامل",
  "home.why6.desc": "بلا قوالب جاهزة. كل حل يُبنى بشكل فريد.",

  "home.cta.eyebrow": "لنعمل معًا",
  "home.cta.title1": "لديك مشروع في بالك؟",
  "home.cta.title2": "لنبنِ شيئًا",
  "home.cta.title2Highlight": "مذهلاً.",
  "home.cta.scheduleCall": "احجز مكالمة",
  "home.cta.whatsapp": "تواصل عبر واتساب",

  // ---- About.dc.html ----
  "about.hero.badge": "من نحن",
  "about.hero.title": "الفريق وراء إطلاقك <span style=\"background: linear-gradient(100deg, #00CFFF 20%, #3B82F6 50%, #00CFFF 80%); background-size: 200% auto; -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; animation: nvShimmer 5s linear infinite;\">الكبير القادم</span>",
  "about.hero.subtitle": "Next Vision Agency فريق صغير من الخبراء المتفانين في إتقان الحرفة — نصمّم منتجات رقمية تبدو بجمالٍ يضاهي أداءها.",
  "about.story.badge": "قصتنا",
  "about.story.title": "انطلقنا من فكرة بسيطة",
  "about.story.paragraph1": "انطلقت Next Vision Agency قبل ثلاث سنوات من قناعة راسخة: المنتجات الرقمية الاستثنائية تُصنع على يد فرق صغيرة تهتم بكل بكسل وكل سطر برمجي.",
  "about.story.paragraph2": "اليوم نتشارك النجاح مع رواد الأعمال والمؤسسات الكبرى على حدٍ سواء، ونتعامل مع كل مشروع — كبيرًا كان أم صغيرًا — بنفس الشغف بالإتقان والسرعة والنتائج القابلة للقياس.",
  "about.values.badge": "ما يحرّكنا",
  "about.values.title": "قيمنا الأساسية",
  "about.values.card1.title": "الإتقان قبل الاختصارات",
  "about.values.card1.description": "نهتم بالتفاصيل التي يتجاهلها الآخرون — فهذا ما يفرّق بين الجيد وما لا يُنسى.",
  "about.values.card2.title": "سرعة ذات هدف",
  "about.values.card2.description": "نتحرك بسرعة دون التضحية بالجودة — زخم مدعوم بالانضباط.",
  "about.values.card3.title": "شراكة حقيقية",
  "about.values.card3.description": "أهدافك تصبح أهدافنا. نلتزم بالصدق والشفافية والانخراط الكامل في تحقيق نتائجك.",
  "about.timeline.badge": "محطات بارزة",
  "about.timeline.title": "مسيرتنا حتى الآن",
  "about.timeline.step1.title": "تأسيس الوكالة",
  "about.timeline.step1.description": "انطلقنا بفريق من شخصين وعميل واحد.",
  "about.timeline.step2.title": "تسليم أكثر من 10 مشاريع",
  "about.timeline.step2.description": "توسّع الفريق وأنجزنا مشاريع عبر الويب والجوال.",
  "about.timeline.step3.title": "عملاء دوليون",
  "about.timeline.step3.description": "توسعنا لخدمة عملاء في ثلاث قارات.",
  "about.timeline.step4.title": "أكثر من 50 مشروعًا وفي نمو مستمر",
  "about.timeline.step4.description": "فريق خبير، ومنهجية مثبتة، والكثير قادم في الطريق.",
  "about.cta.title": "هل أنت مستعد للعمل مع فريق <span style=\"color: #00CFFF; text-shadow: 0 0 30px rgba(0,207,255,0.5);\">يهتم فعلًا؟</span>",
  "about.cta.button": "تواصل معنا",

  // ---- Services.dc.html ----
  "services.hero.badge": "ما نقدمه",
  "services.hero.title": "خدمات مصممة من أجل <span style=\"background: linear-gradient(100deg, #00CFFF 20%, #3B82F6 50%, #00CFFF 80%); background-size: 200% auto; -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; animation: nvShimmer 5s linear infinite;\">نمو حقيقي</span>",
  "services.hero.subtitle": "من أول بكسل إلى الإطلاق النهائي، نبني الأساس الرقمي الذي تحتاجه علامتك التجارية للمنافسة والفوز.",
  "services.cards.web.title": "تصميم وتطوير المواقع",
  "services.cards.web.description": "مواقع إلكترونية أنيقة ومتجاوبة، مصممة هندسيًا لتحميل سريع وتحويل الزوار إلى عملاء.",
  "services.cards.web.feature1": "تصميم واجهات وتجربة مستخدم مخصص",
  "services.cards.web.feature2": "تصميم متجاوب مع جميع الأجهزة",
  "services.cards.web.feature3": "تحسين الأداء",
  "services.cards.mobile.title": "تطبيقات الجوال",
  "services.cards.mobile.description": "تطبيقات iOS وAndroid عالية الأداء، مبنية بإحساس أصلي وبنية معمارية متينة.",
  "services.cards.mobile.feature1": "تطبيقات أصلية لـ iOS وAndroid",
  "services.cards.mobile.feature2": "بناء عبر منصات متعددة",
  "services.cards.mobile.feature3": "النشر على متاجر التطبيقات",
  "services.cards.brand.title": "الهوية البصرية",
  "services.cards.brand.description": "هويات بصرية قوية لا تُنسى — شعار، ألوان، وإرشادات — تبني ثقة دائمة.",
  "services.cards.brand.feature1": "الشعار والنظام البصري",
  "services.cards.brand.feature2": "إرشادات الهوية التجارية",
  "services.cards.brand.feature3": "المواد التسويقية",
  "services.cards.uiux.title": "تصميم واجهة وتجربة المستخدم",
  "services.cards.uiux.description": "تصميم منتجات مبني على البحث، يجعل التجارب المعقدة تبدو سهلة وسلسة.",
  "services.cards.uiux.feature1": "أبحاث واختبارات المستخدم",
  "services.cards.uiux.feature2": "الإطارات الأولية والنماذج التجريبية",
  "services.cards.uiux.feature3": "أنظمة التصميم",
  "services.process.badge": "منهجية عملنا",
  "services.process.title": "كيف نحول الأفكار إلى واقع",
  "services.process.step1.title": "الاكتشاف",
  "services.process.step1.description": "نتعمق في أهدافك ومستخدميك وسوقك لتحديد الاستراتيجية الصحيحة.",
  "services.process.step2.title": "التصميم",
  "services.process.step2.description": "تتحول الإطارات الأولية إلى واجهات أنيقة ومتوافقة مع الهوية، مبنية على بحث حقيقي.",
  "services.process.step3.title": "التطوير",
  "services.process.step3.description": "كود نظيف وقابل للتوسع يُحيي التصميم عبر كل جهاز.",
  "services.process.step4.title": "الإطلاق",
  "services.process.step4.description": "نطلق، نراقب، وندعم — ليستمر الأداء المتميز بعد الإطلاق بوقت طويل.",
  "services.cta.title": "لست متأكدًا من الخدمة المناسبة؟ <span style=\"color: #00CFFF; text-shadow: 0 0 30px rgba(0,207,255,0.5);\">لنتحدث.</span>",
  "services.cta.button": "احجز استشارة مجانية",

  // ---- Portfolio.dc.html ----
  "portfolio.hero.badge": "أعمالنا",
  "portfolio.hero.title": "مشاريع <span style=\"background: linear-gradient(100deg, #00CFFF 20%, #3B82F6 50%, #00CFFF 80%); background-size: 200% auto; -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; animation: nvShimmer 5s linear infinite;\">تتحدث عن نفسها</span>",
  "portfolio.hero.subtitle": "مجموعة مختارة من المنتجات والعلامات التجارية والمنصات التي ساعدنا في تحقيقها.",
  "portfolio.filter.all": "جميع المشاريع",
  "portfolio.filter.web": "تطوير المواقع",
  "portfolio.filter.mobile": "تطبيقات الجوال",
  "portfolio.filter.branding": "الهوية التجارية",
  "portfolio.project.ecommerce.title": "منصة تجارة إلكترونية",
  "portfolio.project.ecommerce.category": "تطوير المواقع",
  "portfolio.project.fooddelivery.title": "تطبيق توصيل الطعام",
  "portfolio.project.fooddelivery.category": "تطبيق جوال",
  "portfolio.project.techstartup.title": "هوية شركة تقنية ناشئة",
  "portfolio.project.techstartup.category": "الهوية التجارية",
  "portfolio.project.realestate.title": "بوابة عقارية",
  "portfolio.project.realestate.category": "تطوير المواقع",
  "portfolio.project.fittrack.title": "تطبيق FitTrack للياقة البدنية",
  "portfolio.project.fittrack.category": "تطبيق جوال",
  "portfolio.project.horizon.title": "لوحة تحكم Horizon SaaS",
  "portfolio.project.horizon.category": "تطوير المواقع",
  "portfolio.project.aurora.title": "إعادة تصميم هوية Aurora لمستحضرات البشرة",
  "portfolio.project.aurora.category": "الهوية التجارية",
  "portfolio.project.marche.title": "هوية متجر Marché",
  "portfolio.project.marche.category": "الهوية التجارية",
  "portfolio.stats.projects.label": "مشروعًا تم إنجازه",
  "portfolio.stats.industries.label": "قطاعًا تمت خدمته",
  "portfolio.stats.rating.label": "متوسط تقييم العملاء",
  "portfolio.stats.delivery.label": "تسليم في الموعد المحدد",
  "portfolio.cta.title": "هل تريد نتائج مماثلة <span style=\"color: #00CFFF; text-shadow: 0 0 30px rgba(0,207,255,0.5);\">لعلامتك التجارية؟</span>",
  "portfolio.cta.button": "ابدأ مشروعك",

  // ---- Project.dc.html ----
  "project.back": "العودة إلى الأعمال",
  "project.visit": "زيارة المشروع المباشر",
  "project.startSimilar": "ابدأ مشروعًا مشابهًا",
  "project.gallery": "معرض الصور",
  "project.notFound.title": "المشروع غير موجود",
  "project.notFound.desc": "ربما تمت إزالة هذا المشروع أو أن الرابط غير صحيح.",
  "project.notFound.cta": "العودة إلى الأعمال",

  // ---- Contact.dc.html ----
  "contact.hero.badge": "تواصل معنا",
  "contact.hero.title": "لنبنِ شيئاً <span style=\"background: linear-gradient(100deg, #00CFFF 20%, #3B82F6 50%, #00CFFF 80%); background-size: 200% auto; -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; animation: nvShimmer 5s linear infinite;\">مذهلاً معاً</span>",
  "contact.hero.subtitle": "أخبرنا عن مشروعك — نرد عادةً خلال يوم عمل واحد.",
  "contact.form.name.label": "الاسم الكامل",
  "contact.form.name.placeholder": "سارة أحمد",
  "contact.form.email.label": "البريد الإلكتروني",
  "contact.form.whatsapp.label": "رقم واتساب",
  "contact.form.whatsapp.placeholder": "+213 555 123 456",
  "contact.form.country.label": "الدولة",
  "contact.form.country.placeholder": "الجزائر",
  "contact.form.subject.label": "الموضوع",
  "contact.form.subject.placeholder": "أخبرنا بما تحتاجه",
  "contact.form.message.label": "تفاصيل المشروع",
  "contact.form.message.placeholder": "شاركنا بعض التفاصيل حول مشروعك والجدول الزمني والميزانية.",
  "contact.info.email.label": "راسلنا عبر البريد",
  "contact.info.phone.label": "اتصل بنا",
  "contact.info.address.label": "زُرنا",
  "contact.info.address.value": "الجزائر العاصمة، الجزائر",
  "contact.whatsapp.label": "تحدث معنا عبر واتساب"
};
